import Head from 'next/head';
import Link from "next/link";

import axios from "./configs/axios";

function Home(props) {

  console.log(props);
  return (
    <div className="container mx-auto my-10">
      <Head>
        <title>Microservice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-white rounded-md p-5 shadow-lg">
        <h1 className="font-bold text-xl flex justify-center">NEXT JS FRONTPAGE</h1>
        <Link href="/courses">
          <a>To Random Page</a>
        </Link>
      </main>
    </div>
  );
}

Home.getInitialProps = async () => {
  try {
    const data = await axios.get(`/courses`);
    return data;
  } catch (error) {
    return error;
  }
};

export default Home;