import Head from 'next/head'


export default function Home() {
  return (
    <div className="container mx-auto my-10">
      <Head>
        <title>Microservice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-white rounded-md p-5 shadow-lg">
        <h1 className="font-bold text-xl flex justify-center">NEXT JS FRONTPAGE</h1>
      </main>
    </div>
  );
}
