import Head from 'next/head'


export default function Home() {
  return (
    <div className="container mx-auto mt-10">
      <Head>
        <title>Microservice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-10">
        <h1>Main Page</h1>
      </main>
    </div>
  );
}
